on: push

jobs:
    project-a-or-project-b:
        runs-on: ubuntu-latest
        name: Project A or Project B

        steps:

        - name: Checkout Main repository
          uses: actions/checkout@v2
          run: echo "Hallo how are you?"

          
